# Generated by Django 4.0.2 on 2022-02-18 22:11

import candidate_scoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Candidate Name')),
                ('reference', models.CharField(max_length=8, unique=True, validators=[candidate_scoring.models.validator_ref], verbose_name='Candidate Score')),
            ],
        ),
    ]
