# Generated by Django 4.0.2 on 2022-02-18 22:55

import candidate_scoring.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='reference',
            field=models.CharField(max_length=8, unique=True, validators=[candidate_scoring.models.validator_ref], verbose_name='Candidate Reference'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[candidate_scoring.models.validate_score], verbose_name='Candidate Score')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_scoring.candidate')),
            ],
        ),
    ]
