# Generated by Django 4.0.2 on 2022-02-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0002_alter_candidate_reference_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='reference',
            new_name='candidate_ref',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='candidate',
            new_name='candidate_ref',
        ),
    ]
