# Generated by Django 4.0.2 on 2022-02-18 23:50

import candidate_scoring.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0003_rename_reference_candidate_candidate_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_ref',
            field=models.CharField(max_length=8, validators=[candidate_scoring.models.validator_ref], verbose_name='Candidate Reference'),
        ),
        migrations.AlterField(
            model_name='score',
            name='candidate_ref',
            field=models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='candidate_scoring.candidate', validators=[candidate_scoring.models.validator_ref]),
        ),
    ]
