# Generated by Django 4.0.2 on 2022-02-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0004_alter_candidate_candidate_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='candidate_ref',
            new_name='candidate',
        ),
    ]
