# Generated by Django 4.0.2 on 2022-02-19 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0005_rename_candidate_ref_score_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='candidate',
        ),
        migrations.AddField(
            model_name='score',
            name='candidate_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='candidate_scoring.candidate'),
        ),
    ]
