# Generated by Django 4.0.2 on 2022-02-19 15:08

import candidate_scoring.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0015_candidate_id_alter_candidate_candidate_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_ref',
            field=models.CharField(max_length=8, unique=True, validators=[candidate_scoring.models.validator_ref], verbose_name='Candidate Reference'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Candidate Name'),
        ),
        migrations.AlterField(
            model_name='score',
            name='candidate_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_scoring.candidate'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(validators=[candidate_scoring.models.validate_score], verbose_name='Candidate Score'),
        ),
    ]
