# Generated by Django 4.0.2 on 2022-02-19 15:14

import candidate_scoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0016_alter_candidate_candidate_ref_alter_candidate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_ref',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[candidate_scoring.models.validator_ref], verbose_name='Candidate Reference'),
        ),
    ]
