# Generated by Django 4.0.2 on 2022-02-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0017_remove_candidate_id_alter_candidate_candidate_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='candidate_ref',
            new_name='candidate_ref_score',
        ),
    ]
