# Generated by Django 4.0.2 on 2022-02-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0018_rename_candidate_ref_score_candidate_ref_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='candidate_ref_score',
            new_name='candidate_ref',
        ),
    ]
