# Generated by Django 4.0.2 on 2022-02-19 15:24

import candidate_scoring.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0019_rename_candidate_ref_score_score_candidate_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_ref',
            field=models.CharField(max_length=8, validators=[candidate_scoring.models.validator_ref], verbose_name='Candidate Reference'),
        ),
        migrations.AlterField(
            model_name='score',
            name='candidate_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidate_scoring.candidate'),
        ),
    ]
