# Generated by Django 4.0.2 on 2022-02-19 23:37

import candidate_scoring.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_scoring', '0021_score_id_alter_score_candidate_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_ref',
            field=models.CharField(max_length=8, unique=True, validators=[candidate_scoring.models.validator_ref], verbose_name='Candidate Reference'),
        ),
        migrations.AlterField(
            model_name='score',
            name='candidate_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='candidate_scoring.candidate'),
        ),
    ]
